### PR TITLE
Updated compatibility with Redmine 3.0 and Rails 4

### PR DESCRIPTION
**Pull request by jancybsec**

### CODE REVIEW

**Comment by kenji21** [comment]
Changes of this PR + rollback of 
this : https://github.com/kulesa/redmine_better_gantt_chart/blob/50c323fe8b6ac667c88bd2b68c2d9ad655c61ce0/app/helpers/application_helper.rb

make it OK for redmine 3.4.2.stable

**Comment by kulesa** [comment]
@kenji21 thanks! Can you open a pull request for this? I'm not maintaining this actively and having difficulties figuring out what changes need to be done.

**Comment by kenji21** [comment]
just done with PR#129

**Comment by kenji21** [comment]
👍

**Pull request closed without merging**
